language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls

script: make test

branches:
  only:
    - master

after_success:
  - coveralls
