name: Tests

on: [push, pull_request]

env:
  PYTHONWARNINGS: error

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: setup
        run: |
          python -m pip install --user pipx
          python -m pipx install poetry
          poetry install --no-interaction --no-ansi
      - run: poetry run ./manage.py migrate
      - run: poetry run coverage run manage.py test
      - run: poetry run python -m pip install "git+https://github.com/${GITHUB_REPOSITORY}.git#egg=nmdmail"

      - uses: codecov/codecov-action@v3
